import os
from dotenv import load_dotenv

load_dotenv()

BINANCE_API_KEY = os.getenv("BINANCE_API_KEY", "")
BINANCE_API_SECRET = os.getenv("BINANCE_API_SECRET", "")
FISCAL_YEAR_START_MONTH = 1
FISCAL_YEAR_END_MONTH = 12
EUR_SYMBOL = "EUR"
FIFO_METHOD = "FIFO"
SPANISH_TAX_RATE_GENERAL = 0.19
SPANISH_TAX_RATE_SAVINGS_6000 = 0.21
SPANISH_TAX_RATE_SAVINGS_50000 = 0.23
SPANISH_TAX_RATE_SAVINGS_200000 = 0.27
SPANISH_TAX_RATE_SAVINGS_OVER = 0.28
